spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.22.190:3306/pendulum?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # jpa配置
  jpa:
    show-sql: false
    open-in-view: false
  # rabbitmq配置
  rabbitmq:
    host: 192.168.22.203
    port: 5672
    username: admin
    password: 123456
    virtual-host: scheduled_vhost
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
